services:
  app:
    env_file: .env
    build: .
    container_name: blog_django
    ports:
      - "5173:5173"
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  webserver:
    image: nginx:latest
    volumes:
      - ./.config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    ports:
      - "5174:80"
    depends_on:
      - app